version: '3.8'

services:

  backend:
    build: ./foodiesapi
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/foods"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"

  frontend-user:
    build: ./foodies
    ports:
      - "3000:80"
    depends_on:
      - backend

  frontend-admin:
    build: ./adminpanel
    ports:
      - "3001:80"
    depends_on:
      - backend
