version: '3.8'

services:

  backend:
    build: ./foodiesapi
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/foods"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"

  frontend-user:
    build: ./foodies
    ports:
      - "3000:80"
    depends_on:
      - backend

  frontend-admin:
    build: ./adminpanel
    ports:
      - "3001:80"
    depends_on:
      - backend

  prometheus:
   image: prom/prometheus
   container_name: prometheus
   ports:
    - "9090:9090"
   volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
   depends_on:
    - backend

  grafana:
   image: grafana/grafana
   container_name: grafana
   ports:
    - "3002:3000"
   depends_on:
    - prometheus
